# Generated by Django 6.0.6 on 2026-06-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='converted_file',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/converted/%Y/%m/%d/'),
        ),
    ]
