# Generated by Django 6.0.6 on 2026-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_floorplan_converted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='supabase_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
